language: node_js
node_js:
  - '5'
  - '4'
  - '4.4'
  - '4.3'
  - '4.2'
  - '4.1'
  - '4.0'
services:
- mongodb
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
notifications:
  email: false
  slack:
    secure: HK8TbLXTOKavXhPCrYsMNhACPZq9dzC+k/Exzkj80cmyOiZi0IYulhK3HXydPhMRcNc9sFHWJfImoEkniZOk424HWw48cf7lPdEB/w/zu2/mW7uiqnSDrMqguHZqvuLXKgJPZ8pOrOGroyabsqqnRmJGpcGUumEqwtdX+VajHNjxpCZiQjGGu+oHW4EEL1fnWFG/U0ONcu34etZwvS8xXby8ZkTJgCIQZDv3uqWyu2DHca4eSpfyfu7TZ3nzMQx4TbYUFHpt+Cq6f7Tsn1VAADncPrk15FaSlZ9xhaE60szE3u16Myzu6k4MfybGsVoFsdy6HsEMsR/+bKFBjlZorTBGUWAODqlLMc2tHz+WaojdJeDIcGoZ+s0lE8kaFbWDEOfrAw4Cb4170I8ZIz6fq2MK7gfdEFXO/E5SvquZS5aPgezBr1xHdT2V+qoSZhDf6qmzE1ih+Ja+FpvM8zWzOiCP8bi268MxhV5OWFQh3QJcSxn38kJjuQREUxX56bVtOYupN9YI+E2fiftNRaM4IXtw4EWydjZZyOCrReGcS7MMKVNYQ9cqBww07h0NstZqGySd6zRvJPltiQ3j72El9AIulGNM0zCaoQ4EdjPyqySfOK51xDN8d6VSQ4ruYF63Fffc77X2siYbX6b08spshyoWd1swo+/+Ochemj1+H3U=
deploy:
  provider: npm
  email: jason@centralping.com
  api_key:
    secure: TqoRbWJiT6P4+CKxC6pCPsjZcvtAZySbVt5KxYcmI8lnnB6z79SQoF78uHuKGl21NGad9WouErEttdys6uXLXcRamRGTM3xbgP1XqjTiH09VT5mdqXNlncEvuLjPg6ifknVvwQzsKGOdN3mbarWO82kJzquYsKHnd5PT0omoBJcjUMkn36DSdd0FHyX7cxnhE1NSbkJq92V1cD5rQSvwS6fCLsd/5GxT8VPbO6S6eUeKymOxWLJfhFfNQYcAuDNIEqKM2ZMGxgUSYbzIe83136t2vpCKkAodJiJtYv5TM/xuyLA5QYWXSCnecYLoWRfJOEtCzsngYK+ZJ4pHvqUw4niOq4K/4+O1L/KKmB8xpmBJdsyh9VK+nl5JChE+XEgBb1OsUACQvNSUuIbM7zJc5xCM+XqsQfM5XIfYag5fm6Hzd+f5AtXO1+AXgSD/dsO4tqD89pCGoZT17tnXPqM476WUNHrcpSNINBTbXnJuJS1ujJpvSZcUf3klG5o22jYtRQBd4CFQj8AJGvKwUzkXJ9ekhHllIviAAv0N8qWZ+7m5SYsMDlyJKQu0jb/FSWQCsCD9WUUxNQmnO44L5coI8sW5AjX8/2S/3OPoFKgIxY5YM6eDW2uk24UInvdnxjyo2OO8rD2ePYF4dl8LdH0FV+XIlSp0dHHbmpAoWq0mGcY=
  on:
    tags: true
    repo: CentralPing/mongoose-plugin-tags
